{% set commit_hash = 'f7065b29130b3d35bf62967f4627188865faee44' %}

package:
  name: "ftgl"
  version: 2.1.3

source:
  url: https://github.com/frankheckenbach/ftgl/archive/{{ commit_hash }}.zip
  fn: ftgl-{{ commit_hash }}.zip

build:
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}   # [linux]
    - cmake

  host:
    - freetype
    - libglu  # [linux]
  
  run:
    - freetype

about:
  home: http://sourceforge.net/projects/ftgl/
  license: MIT
