package:
  name: ftgl
  version: 2.1.3

source:
  git_url: https://github.com/ulrichard/ftgl.git
  git_tag: master

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - freetype
    - cmake
  
  run:
    - freetype

about:
  home: http://sourceforge.net/projects/ftgl/
  license: GNU LGPLv2
