{% set name = "ftgl" %}
{% set branch = "master" %}

package:
  name: {{ name }}
  version: 2.1.3

source:
  url: https://github.com/frankheckenbach/ftgl/archive/bceab5929f62a8adf5ddf68401d45ebe790260da.zip
  fn: ftgl-bceab5929f62a8adf5ddf68401d45ebe790260da.zip

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}   # [linux]
    - cmake

  host:
    - freetype
    - libglu  # [linux]
  
  run:
    - freetype

about:
  home: http://sourceforge.net/projects/ftgl/
  license: GNU LGPLv2
