{% set name = "ftgl" %}
{% set branch = "2.3.1" %}

package:
  name: {{ name }}
  version: {{ branch }}

source:
  url: https://github.com/frankheckenbach/{{ name }}/archive/{{ branch }}.zip
  fn: {{ name }}-{{ branch }}.zip

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}   # [linux]
    - cmake

  host:
    - freetype
    - libglu  # [linux]
  
  run:
    - freetype

about:
  home: http://sourceforge.net/projects/ftgl/
  license: MIT
