{% set name = "ftgl" %}
{% set branch = "master" %}

package:
  name: {{ name }}
  version: 2.1.3

source:
  fn: ftgl-2.1.3-rc5.tar.gz  # [not win]
  url: http://www.mirrorservice.org/sites/downloads.sourceforge.net/f/project/ft/ftgl/FTGL%20Source/2.1.3~rc5/ftgl-2.1.3-rc5.tar.gz  # [not win]
  url: https://github.com/ulrichard/{{ name }}/archive/{{ branch }}.tar.gz  # [win]
  fn: {{ name }}-{{ branch }}.tar.gz                                        # [win]

build:
  number: 1

requirements:
  build:
    - freetype
    - cmake     # [win]
  
  run:
    - freetype

about:
  home: http://sourceforge.net/projects/ftgl/
  license: GNU LGPLv2
