{% set commit_hash = '209963ab18f4c46c8489e32b1cc48e2610012998' %}

package:
  name: "ftgl"
  version: 2.1.3

source:
  url: https://github.com/cryoem/ftgl/archive/{{ commit_hash }}.zip
  fn: ftgl-{{ commit_hash }}.zip

build:
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}   # [linux]
    - cmake
    - gnuconfig
    - autoconf
    - automake
    - libtool
    - make                               # [unix]

  host:
    - freetype
    - libglu  # [linux]
  
  run:
    - freetype

about:
  home: http://sourceforge.net/projects/ftgl/
  license: MIT
