# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ZM1Tk6/PIHqwbPs1Z+htUMcZWfzyMsmJOqaCBwU8SnLxx9lJj2/RO/a/H0/hpZPQtmn+P/GqadHqMARkf9dK9IQaK7r5ZbKykw/6dvJ0rdyXnqWGkJAn421sgc959QPdglSSc8altJzAYjTtlPDMY+s67HE66Mvo4LILMl703mP97I1IqJBC299zevwYqE1dvKw19KTCCM5tg7vKSq2kMNsvb4zc4I5hY0i3HdIMMmkDVp/lcT8DG0/LHfr3+qOcy+sveXaF9u+BBk7KtPzkeWq8b1/pjxQSL00Ke/RnNBtj5xe60stQfwOVYTOjHFdO3TUlet6rCBKLGh5HH2jn6s58qyxUEnCCGWl01cQLP/p6YDXgt4Sp3V4QyrZDxqafg5+bUMS8REOi65N3JE8EITSWKLqG5YMed/mA8OaV8XYGKdW03kgSt8IjHoiWSPugTw0foHb+Wyz3Me6Y3Jrq76nLcPq2uukA4uIsEbOwf+hS5WeV8o3d15/m79SbhQUJ5qCdiqdWHk0cGU47o71d6BILKq6Pqz36S14hs/FAO/Plz4PCaC5pmCDisMiRgvw326LMdku03AOBqXh1jO1KmqZd5cQKll2rApP2XzanOH6g4aXWvOH98GWp+hnORDT/aECI3OeS3ecNOLvuRk1KykLOxD4mLkmRXp0ab97CSZw="

matrix:
  include:
    - env: CONFIG=osx_ UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"

  - if [[ ${PLATFORM} =~ .*osx.* ]]; then ./.travis/run_osx_build.sh; fi
