channels:
  sources: [defaults]
  targets:
  - [cryoem, main]
github:
  user_or_org: cryoem
  repo_name: ftgl-feedstock

travis:
  secure:
    BINSTAR_TOKEN: 07rvr0ppIuxHFEszciR5WQ/rWlAjrx2ABj5D6hsZwD6/4ddG40WGiVf2m4hr911z/W/1LGJjELCUE0Hp5ZbsbxRi9m/+L9J1pOb0OFAJVJOqviIsD1858LoDjom703IbqgJ/x5+1XQEgEvgiiRiHRhkY1ABPlhe5b3VyfvZTpvuN8uC+pQHa6S7XjCTTDyhGDH0uCPnHU+wqVCAMGG5WJXguem6MfxDpqORHYEqtTNnmapsOP46bgIEJ0o11ton7k/Cndb3N5P+0vKO0ZOehBMqycvp5iW6HvaqMi3yrpCFlHPwwaNFhgEYClvdizJ33kUy/bV+o3auJAsxMzzmpkfwZDulk5aBkKG85VDilSlMcfJzzTl30Ar4dnZIlJLDmKvRXhn/vlBYB7ZktLvc+Xu3qMJav3IJ3/BWfrTk8GYYPgh3wU9w2VlcVpjFcBhZ/H8hfz3BH2LC+hnMugE0G5BiwcsBvmOwMr2l0bN1JUpyePEreNGjc1NTGwl7O20E+U+lpmucYxJ9633rVpznbCNCeRvTs53nFJv3iKV+WXnQBfjm1oEimpsVLPhuInq1RAPfxAYAjm5koCI995lNY2dgb8OcByZaQScUSw0Ju6Jjvd02/9KfY99U/BAaGp3u6f5NBLOrfu5KHkojeWDxoUX15f8Dt2Umx6gBW+MZQdgU=
appveyor:
  secure:
    BINSTAR_TOKEN: DytmJU8Iq1lbelvMvcsTjak25U7QPYCTMr8QmMzqRw21AmRfcLQhfuNPZtjH13q9
