channels:
  targets:
  - [cryoem, main]
github:
  user_or_org: cryoem
  repo_name: ftgl-feedstock

travis:
  secure:
    BINSTAR_TOKEN: 39RjbaZgDjxO06iW/67GrEZE0HbkFiDUtqvMsA6RbbSASuf6TIiflyD4DOYvE5wG7NdfWT5fVTgMvCxf7zAne5PDncFvgPK074EX7aTiGOkkRlR19UK8RqF7vmCCorfG2tTs742GUtnN9hPBX6ODo7AUtxscs49MPGVDxL/Pn4ynpfnGZVkNBtvsUxiZkrK9CEgk8lYVMAHAFuo/r5jDFwqyRQaCmUUGbdXilXz6fEdmCrSNVSFcoD/DjWiN5B9SWIqVasM3XNerUn/U4BUXgOxSN42oTt99ED9NFR90Q1TQ3tJGeqPEo3O4kf0QyLd8pFqvDyNbJt3xZTl1ddwEE9I+b3EDHLLnoYxG0ByVNZjoc8NLGNIVOSDRWFNt2vxiOcOGgO4TMZXJpnV3JS6CIPeoCFdG5iMYTwFKZZU48cstLnYclTcUZRcGq/7h2qKj1W5UXBiDfhje/FyCxNkMoeet5XYMqXq37jRmRoo6UEjrGWDF8Ryz4rIANyxZ/UxQBsJOKsGfXr4n594sidq3au6GrpO6mcdzpl1elOrRQl5VqQBcCxAHvVYUKv3DjQqDZP9P0Li6f23lkAnf2RorpahJLb7Ss5XGfBO/sFVT3C3neqTXi71K3vFVKTYeDWrxBY4AGSXU9ROL4cyzT48mepv/ndzTHTF+Fc7Ekuo5dNQ=
appveyor:
  secure:
    BINSTAR_TOKEN: OcAUZlpSDgQtX8QAIX7qr8iZhsrOWwlmuyDECE7wAYBRlvXIBJ7BbXhX/Fmz4Oib
